### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by rogueturnip** [stagf15/DSC_Panel#4]
It looks like during a code cleanup a lot of the constants (codes, word bit length, etc).  Causing things not to compile now.

**Comment by stagf15** [comment]
I uploaded the corrected constants file.  It should be working  now.

**Comment by gnalbandian** [comment]
Good to hear that. Good work.

Have you made any progress regarding writing to the bus?

**Comment by rogueturnip** [comment]
Debugging the circuit and the I'm hoping that will help stagf15. One I get
the circuit working I will post the schematic to this GitHub.

**Comment by gnalbandian** [comment]
Great job. Thanks for your work. Let me know if you need help with it regarding testing or whatsoever

**Comment by rogueturnip** [comment]
I'm hoping to have it working this weekend.  I need to. Recalculate some
resistor values because I don't think the optocouplers are activating.
